### ISSUE TITLE
mismatch of library and code example in readme

### ISSUE THREAD

**Issue by beenotung** [zalelion/cqrs#13]
In version 2.10.10,

I got below errors when running the example from the readme:
- Error: please implements updater() Getter!
- TypeError: $.once is not a function

In my IDE, it warm me below methods are not existing:
- $.lock()
- $.once(json,string)
- $.get(string,string)
- $.unlock()

from the Actor.d.ts, I saw
```typescript
lock(data:LockDataType):boolean
unlock(key:any):void
```

These suggest the README may have become out-dated.

console output:
```nodejs
(node:18682) UnhandledPromiseRejectionWarning: Error: please implements updater() Getter!
    at User.get updater [as updater] (/home/beenotung/tmp/p/demo-cqrs/node_modules/cqrs/dist/Actor.js:52:15)
    at Function.apply (/home/beenotung/tmp/p/demo-cqrs/node_modules/cqrs/dist/Service.js:66:35)
    at User.add (/home/beenotung/tmp/p/demo-cqrs/dist/index.js:28:22)
    at run (/home/beenotung/tmp/p/demo-cqrs/node_modules/cqrs/dist/Domain.js:252:65)
    at /home/beenotung/tmp/p/demo-cqrs/node_modules/cqrs/dist/Domain.js:289:37
    at new Promise (<anonymous>)
    at Object.apply (/home/beenotung/tmp/p/demo-cqrs/node_modules/cqrs/dist/Domain.js:225:40)
    at /home/beenotung/tmp/p/demo-cqrs/dist/index.js:73:15
    at Generator.next (<anonymous>)
    at fulfilled (/home/beenotung/tmp/p/demo-cqrs/dist/index.js:4:58)
(node:18682) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18682) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:18682) UnhandledPromiseRejectionWarning: TypeError: $.once is not a function
    at Transfer.<anonymous> (/home/beenotung/tmp/p/demo-cqrs/dist/index.js:53:15)
    at Generator.next (<anonymous>)
    at /home/beenotung/tmp/p/demo-cqrs/dist/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/beenotung/tmp/p/demo-cqrs/dist/index.js:3:12)
    at Transfer.transfer (/home/beenotung/tmp/p/demo-cqrs/dist/index.js:50:16)
    at run (/home/beenotung/tmp/p/demo-cqrs/node_modules/cqrs/dist/Domain.js:252:65)
    at /home/beenotung/tmp/p/demo-cqrs/node_modules/cqrs/dist/Domain.js:289:37
    at new Promise (<anonymous>)
    at Object.apply (/home/beenotung/tmp/p/demo-cqrs/node_modules/cqrs/dist/Domain.js:225:40)
(node:18682) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)


```

sample code:
```typescript
import {Actor, Domain} from "cqrs";

const MongoStore = require('cqrs-mongo-eventstore').default;
const eventstore = new MongoStore("localhost/test");
const domain = new Domain({eventstore});

interface User {
  username: string
}

class User extends Actor {
  name: string;
  amount: number;

  constructor(data: User) {
    super(Object.assign({
      amount: 0,
    }, data))
  }

  changename(name) {
    this.$(name)
  }

  deduct(amount) {
    this.$("deduct", amount)
  }

  add(amount) {
    this.service.apply("add", amount)
  }

  when(event) {
    const data = this.json;
    switch (event.type) {
      case "changename":
        return {name: event.name}
      case "deduct":
        return {amount: data.amount - event.data}
      case "add":
        return {amount: data.amount + event.data}
    }
  }
}

interface Transfer {
  fromUserId: string
  toUserId: string
}

class Transfer extends Actor {
  constructor(data: Transfer) {
    super({finish: false})
  }

  log(event) {
    console.log(event)
  }

  async transfer(fromUserId, toUserId, amount) {
    const $ = this.$;
    $.lock();
    $.once({actorType: "User", type: "add"}, "log");
    const fromUser = await $.get("User", fromUserId)
    const toUser = await $.get("User", toUserId)
    fromUser.deduct(amount)
    toUser.add(amount)
    $.unlock()
    $("finish", null)
  }

  when(event) {
    switch (event.type) {
      case "finish"
        return {finish: true}
    }
  }
}

domain.register(User).register(Transfer);

async function main() {

  let Alice = await domain.create("User", {name: "Alice"})
  Alice.add(100);

  let Bob = await domain.create("User", {name: "Bob"});

  const transfer = await domain.create("Transfer", {});
  await transfer.transfer(Alice.id, Bob.id, 15);

  Alice = await domain.get("User", Alice.id);
  Bob = await domain.get("User", Bob.id);
  console.log("Alice money is", Alice.json.amount);
  console.log("Bob money is", Bob.jsMode.amount);

}

main();
```

**Comment by liangzeng** [comment]
sorry , document no update.  

```js
get updater(){         //  to instead when(event) {
}
```

look https://github.com/liangzeng/cqrs/tree/master/example

```js
module.exports = class User extends Actor {

    constructor(data) {
        super({ money: data.money || 0, name: data.name, id:data.id });
    }

    changename(name) {
        this.$.apply("changename", name);
    }

    get updater(){  // see it
       return {
          changename(data,event){
            return { name: event.name }
          }
       }
    }

}

```
